import streamlit as st
import psycopg2
import time
import re
from datetime import datetime

# ==========================================================
# 1. СЛОВАРЬ ЛОКАЛИЗАЦИИ (RU / EN)
# ==========================================================
LANGUAGES = {
    "RU": {
        "page_title": "Мой Трекер Обучения",
        "title": "🎓 Персональный трекер обучения",
        "metric_courses": "Всего курсов в базе",
        "metric_hours": "Общее время в учебе (часы)",
        "sb_header": "➕ Добавить новый курс",
        "sb_course_name": "Название курса:",
        "sb_placeholder": "например, CS50 Python",
        "sb_lessons_count": "Количество уроков в курсе:",
        "sb_submit": "Создать отслеживание",
        "sb_success": "Курс '{}' успешно добавлен!",
        "tab_active": "🚀 Активные курсы",
        "tab_completed": "📦 Пройденные (Архив)",
        "folder_empty": "В этой папке пока ничего нет.",
        "course_stats": "⏱️ Налетано: **{} ч.** | Пройдено уникальных уроков: **{} из {}**",
        "progress_label": "Прогресс: **{}%**",
        "manage_course": "🗑️ Управление курсом",
        "delete_warn": "Удалить '{}'?",
        "delete_confirm": "Да, удалить окончательно",
        "exp_active_title": "⏳ ИДЕТ ЗАНЯТИЕ! (Нажмите для остановки)",
        "exp_inactive_title": "⚡ Занятие и История уроков",
        "archive_msg": "🎉 Этот курс полностью пройден! Доступен только просмотр истории.",
        "btn_start": "⏱️ Начать занятие",
        "timer_running": "Таймер запущен. Прошло минут: {}",
        "lesson_title_lbl": "Название урока:",
        "lesson_placeholder": "например, Урок 1",
        "comment_lbl": "Что прошли? (комментарий):",
        "mood_lbl": "Ваше настроение:",
        "mood_options": ["🔥 Заряжен / Все понял", "🟢 Хорошо / Двигаюсь дальше", "🟡 Нормально / Сложновато", "🔴 Устал / Ничего не понял"],
        "is_done_lbl": "✅ Этот урок полностью завершен?",
        "btn_stop": "🛑 Завершить сессию",
        "err_format": "🛑 ОШИБКА: Пожалуйста, используйте формат 'Урок X' (например: Урок 1, Урок 2).",
        "err_max_lessons": "🛑 ОШИБКА: В этом курсе запланировано всего {} уроков!",
        "err_already_done": "🛑 ОШИБКА: '{}' уже БЫЛ успешно завершен ранее!",
        "addendum_prefix": "\n✍️ [Дополнение]: ",
        "other_timer_running": "Запущен таймер на другом курсе.",
        "history_title": "**Журнал уроков:**",
        "history_empty": "История пуста.",
        "lesson_status_done": "✅ Завершен",
        "lesson_status_progress": "⏳ В процессе",
        "min_label": "мин.",
        "hist_total_time": "⏱️ `Общее время урока:` **{} мин.** | `🧠 Настроение:` {}",
        "hist_last_update": "📅 `Последнее обновление:` {}",
        "hist_notes": "💬 `Заметки / Комментарии:`",
        "btn_del_lesson": "🗑️ Удалить урок",
        "sidebar_theme": "🎨 Настройки интерфейса",
        "bg_color_label": "Цвет фона",
        "text_color_label": "Цвет текста"
    },
    "EN": {
        "page_title": "My Study Tracker",
        "title": "🎓 Personal Study Tracker",
        "metric_courses": "Total courses in DB",
        "metric_hours": "Total study time (hours)",
        "sb_header": "➕ Add New Course",
        "sb_course_name": "Course name:",
        "sb_placeholder": "e.g., CS50 Python",
        "sb_lessons_count": "Number of lessons in course:",
        "sb_submit": "Create tracking",
        "sb_success": "Course '{}' successfully added!",
        "tab_active": "🚀 Active Courses",
        "tab_completed": "📦 Completed (Archive)",
        "folder_empty": "This folder is currently empty.",
        "course_stats": "⏱️ Study time: **{} hrs** | Unique lessons completed: **{} of {}**",
        "progress_label": "Progress: **{}%**",
        "manage_course": "🗑️ Manage Course",
        "delete_warn": "Delete '{}'?",
        "delete_confirm": "Yes, delete permanently",
        "exp_active_title": "⏳ SESSION IN PROGRESS! (Click to stop)",
        "exp_inactive_title": "⚡ Session & Lesson History",
        "archive_msg": "🎉 This course is fully completed! Only history viewing is available.",
        "btn_start": "⏱️ Start Session",
        "timer_running": "Timer running. Minutes passed: {}",
        "lesson_title_lbl": "Lesson title:",
        "lesson_placeholder": "e.g., Lesson 1",
        "comment_lbl": "What did you cover? (comment):",
        "mood_lbl": "Your mood:",
        "mood_options": ["🔥 Pumped / Got everything", "🟢 Good / Moving forward", "🟡 Normal / A bit tough", "🔴 Tired / Understood nothing"],
        "is_done_lbl": "✅ Is this lesson fully completed?",
        "btn_stop": "🛑 End Session",
        "err_format": "🛑 ERROR: Please use format 'Lesson X' (e.g., Lesson 1, Lesson 2).",
        "err_max_lessons": "🛑 ERROR: Only {} lessons are planned for this course!",
        "err_already_done": "🛑 ERROR: '{}' was ALREADY successfully completed before!",
        "addendum_prefix": "\n✍️ [Addendum]: ",
        "other_timer_running": "Timer is running on another course.",
        "history_title": "**Lesson log:**",
